//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeforeExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int id { get; set; }
        public int studentID { get; set; }
        public int lessonID { get; set; }
        public Nullable<short> exam1 { get; set; }
        public Nullable<short> exam2 { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual Student Student { get; set; }
    }
}
