// <auto-generated />
namespace Week8CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTableAndRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableAndRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202211100823332_addTableAndRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
